### PR TITLE
Add Feather Icons Support

### PR DESCRIPTION
**Pull request by pablo-lp**
Example:

Load feather icons JS files before

```
$('[data-toggle="datetimepicker"]').datetimepicker({
	icons: {
		type: 'feather',
		time: 'clock',
		date: 'calendar',
		up: 'arrow-up',
		down: 'arrow-down',
		previous: 'arrow-left',
		next: 'arrow-right'
	}
});

feather.replace();
```

### CODE REVIEW

**Comment by tonix-tuft** [comment]
Thank you @pablo-lp! Could you please apply your patches to the `fork` branch instead of the `master` branch?

For now, I have kept the `master` branch the same as the original `tempusdominus/bootstrap-4` repo because I was waiting for @Eonasdan to merge my PRs into the original repo and keep master aligned with his project.

Therefore, I have applied all my bugfixes and additional features to the `fork` branch instead, which is the one I published on the [NPM registry](https://www.npmjs.com/tempusdominus-bootstrap) that you end up with then you run `npm install tempusdominus tempusdominus-bootstrap`.

The other option would be for me to merge the `fork` branch into `master` and then we all will continue to work on this project on `master`, instead.

What do you and others think?

For me it doesn't really make a difference, the only thing is that if I merge `fork` into `master` I won't send any further pull request to the original `tempusdominus/bootstrap-4` repo, which kinda makes sense since it seems to be unmaintained.

Let me know!

**Comment by pablo-lp** [comment]
Hi,

Yes, sorry for my mistake

**Comment by tonix-tuft** [comment]
@pablo-lp No problem. OK, I think we can continue to work on `fork` for now then.

Will wait for your PR on the `fork` branch to merge it and release the updated NPM package.

Thank you!

**Comment by pablo-lp** [comment]
OK. Thanks

**Pull request closed without merging**
