### PR TITLE
Return element itself if no target is found

### PR DESCRIPTION
**Pull request by awh-tokyo**
Same as Pull Request #8 but against Master branch.

### CODE REVIEW

**Comment by tonix-tuft** [comment]
Thank you @awh-tokyo, I am ready to merge your PR. Could you just provide a brief snippet/example here describing the use case covered by your PR?

Thank you.

**Comment by awh-tokyo** [comment]
Hi @tonix-tuft,

So, without this PR, all datetimepicker elements must have an ID and must have data-target set to the ID:

```
<input type="text" name="start-date" class="form-control datetimepicker-input" id="datetimepicker5" data-toggle="datetimepicker" data-target="#datetimepicker5"/>
<input type="text" name="end-date" class="form-control datetimepicker-input" id="datetimepicker6" data-toggle="datetimepicker" data-target="#datetimepicker6"/>
```

Once the PR is implemented, the elements whose target is themselves don't require this:

```
<input type="text" name="start-date" class="form-control datetimepicker-input"  data-toggle="datetimepicker"/>
<input type="text" name="end-date" class="form-control datetimepicker-input" data-toggle="datetimepicker"/>
```

Which could be considerably easier for cases where there are an arbitrary number of datetimepicker elements on the page.

**Comment by awh-tokyo** [comment]
FWIW, this addresses https://github.com/tempusdominus/bootstrap-4/issues/271 in the original repo, and possibly https://github.com/tempusdominus/bootstrap-4/issues/348 as well.

**Comment by tonix-tuft** [comment]
Hi @awh-tokyo,

great! `v5.32.0` featuring your PR has been released.

As always, don't hesitate sending other PRs or issues if you find out something which can be improved! See you soon! Thank you!

**Comment by awh-tokyo** [comment]
Thank you very much!  I confirm it's working now in the package.  Thanks so much for picking up the baton and continuing the development of this component.  I'll let you know if I find more.

**Pull request merged**
