### PR TITLE
Return element itself if no target is found

### PR DESCRIPTION
**Pull request by awh-tokyo**
This is the same change originally submitted by @christopheg at https://github.com/tempusdominus/bootstrap-4/pull/306/

It means that the data-target attribute is no longer required and it can function just with just a class as selector.

### CODE REVIEW

**Comment by tonix-tuft** [comment]
Thank you for your PR @awh-tokyo!

Could you apply your changes to the `master` branch instead of the `fork` branch?

The `fork` branch is an old branch which was not up to date with `master` (indeed, I have aligned it right now and I am seeing a conflict).
`fork` was used before when I was waiting for the original maintainer of `tempusdominus` (Eonasdan) to merge all my changes to its original repo.
Now we have decided to continue working directly on `master`.

Will wait for these changes, but on the master `branch`.

Thank you!

**Comment by awh-tokyo** [comment]
Are you still rebuilding the minified Javascript files before making a version commit?  In that case I can remove the changes from the minified Javascript from the pull request and it should be good to go into master branch.

**Comment by awh-tokyo** [comment]
Actually, I'm closing this and will try again.

**Comment by tonix-tuft** [comment]
> Are you still rebuilding the minified Javascript files before making a version commit? In that case I can remove the changes from the minified Javascript from the pull request and it should be good to go into master branch.

Yes, right now, at least for now, each time I publish a new version I am rebuilding `/build` folder as in the original repo.

During development, you can use `npm run watch` so that Grunt rebuilds the project each time you modify the code and save, validating it with the ESLint rules.

**Pull request closed without merging**
